[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "codex-db-sdk"
version = "0.1.1"
description = "Codex DB Python SDK"
authors = [
    { name = "Everton M. Jesus", email = "evertonmj@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }

[project.urls]
Homepage = "https://github.com/evertonmj/codex"
