apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "codex.fullname" . }}-config
  labels:
    {{- include "codex.labels" . | nindent 4 }}
data:
  CODEX_PORT: "{{ .Values.server.port }}"
  CODEX_HOST: "{{ .Values.server.host }}"
  CODEX_SHUTDOWN_TIMEOUT: "{{ .Values.server.shutdownTimeout }}"
  CODEX_KUBERNETES: "{{ .Values.server.kubernetesMode }}"
  CODEX_LEDGER_MODE: "{{ .Values.database.ledgerMode }}"
  CODEX_NUM_BACKUPS: "{{ .Values.database.numBackups }}"
  CODEX_COMPRESSION: "{{ .Values.database.compression }}"
  CODEX_COMPRESSION_LEVEL: "{{ .Values.database.compressionLevel }}"
  CODEX_LOG_LEVEL: "{{ .Values.logging.level }}"
